### PR TITLE
Add console command

### PR DESCRIPTION
**Pull request by lucapette**
This pull request is **not** meant to be merged, I just want to start a discussion about what I'd like to do. I wrote a naive draft of a `spin console` that would, unsurprisingly, fire up a new rails console in the preloaded app. 

This version is working but is far from being ready. It lacks:
- tests
- documentation
- clean-up/refactoring due to code duplication

And maybe it's missing something else I can't see now. So if you like the idea of having `spin console` I'll proceed with it and take care of the lacking parts. It would be a pleasure to add such a nice command to a project I like/use so much. Furthermore, I'd like to have your opinion how you think we should test the feature and if you think there is a better/different approach I might have to consider to achieve the same goal.

One thing that is worth noticing is that I had to change pre-loading from `config/application.rb` to `config/environment.rb` to actually have the app loaded in the console. Not sure if this can be handled in a better way.

If we are going to finally merge it, this pull request would close the issue #10.

### CODE REVIEW

**Comment by kirs** [comment]
Thanks for your code and ideas!

I guess as long as [Spring officially became part of Rails](https://github.com/rails/spring/commit/59722afea6afc5919a132c5a6e403434e61a4c29) we don't really need "one more" rake or rails console preloader. Did you try it?

**Comment by lucapette** [comment]
oh! I didn't know that spring is now the official way. I didn't try it, I had a look at the code and it looks scarily complicated compared to spin. But your point makes perfectly sense. So I guess it's probably not worth the effort and we can close this one and #10 too :)

**Comment by kirs** [comment]
Yeah. Also Spring will be enabled since Rails 4.1 by default in each app.

**Comment by lucapette** [comment]
So closing this one to clean up :)

**Pull request closed without merging**
