### PR TITLE
Unify run outputs with inspect

### PR DESCRIPTION
**Pull request by rosic**
Fixes spec for 1.8.7.

### CODE REVIEW

**Comment by kirs** [comment]
Are you 100% sure? https://travis-ci.org/jstorimer/spin/jobs/7574153

**Comment by rosic** [comment]
Well, I was as I ran them before pushing, but now..

```
~/dev/ruby/spin (fix-rspec-trailing-args) (1.9.3-p392@spin) > rspec
....................

Finished in 26.05 seconds
20 examples, 0 failures
```

Are the specs 100% stable? I have a newer patch level, but still, the `inspect` should not cause that failure and spec/change does not even seem related. Could you try to rerun that build, just to see the effect?

**Comment by rosic** [comment]
I've just tried locally with `p327`, also all passing. I'm not able to reproduce this now

**Comment by kirs** [comment]
Yeah, there's something very strange with CI. Almost each time I restart it, I get the new kind of failure.
And I really appreciate your help. Sorry for the doubts about your specs :)

**Pull request merged**
