### PR TITLE
Preload rspec with the server start

### PR DESCRIPTION
**Pull request by maprihoda**
I added a short code that preloads rspec in the serve function. On my box, when specing with RSpec, it results in a 4-5 seconds speed up on each test run, which I think is worth it.

I also added a short description to the documentation explaining how to run the whole test suite. This was unclear to me when I was first reading the docs.

And, BTW, thanks for your work, Spin works great for me so far.

### CODE REVIEW

**Comment by bittersweet** [comment]
I tried this out just now but I think it needs a little more work. 

Because you moved the [determine_test_framework](https://github.com/maprihoda/spin/blob/381ec3f4aaa44e9038a763e1b06b2c85e069ee02/bin/spin#L51) call up it does not detect Rspec correctly without using force_rspec. The problem is that RSpec is not defined at that point, it probably gets defined when loaded the application.rb file, I'm not quite sure.

I shaved about 0.5 seconds off my medium sized test suite so great work so far!

**Comment by bittersweet** [comment]
I just checked out your new version and it works like a charm. 

I'll take every speedup I can get and I think that's in the spirit of this gem, what do you think @jstorimer ?

**Comment by jstorimer** [comment]
Great work guys. I had to test it out myself to believe it, but it's a big time saver :)

Thanks!

**Comment by jstorimer** [comment]
Released with v0.2.1.

**Comment by bittersweet** [comment]
Nice one! I was wondering if preloading test_helper.rb or spec_helper.rb would preload for example rspec and every test related gem just like this pullrequest does, I have 6/7 gems in my test group so we might be able to speed it up even more.
I'm not quite sure if it's possible just throwing this out there.

**Comment by maprihoda** [comment]
Preloading spec_helper.rb would also preload config/environment (provided that you load/require config/environment in your helper file, which you normally do for Rails apps). That's a problem because it would also load your app files, which would mean you would have to restart Spin if you changed you app files; otherwise, your tests would fail (like they do with Spork if you don't write your tests first).

One solution is to put your other files in the array in the serve function like e.g. this: ['rspec', 'rspec/rails', 'rspec/autorun', 'capybara/rspec', 'capybara/rails'].each do |gem| ... But I'm not sure if this is a viable solution...

**Comment by bittersweet** [comment]
I see, could we get that list out of bundler somehow assuming that it is setup correctly?

**Comment by jstorimer** [comment]
I'm confused about why this is even an issue. There's a line in `config/application.rb` that does a `Bundler.require(Rails.env)`. That should require all of the gems defined for the test environment.

If gems aren't being preloaded already then Spin isn't working as it should and we should investigate that before trying to shim in this feature. I'll investigate later tonight.

**Comment by bittersweet** [comment]
I'm beginning to get confused as well. If I check the output of the `require gem` bit it doesn't seem to do anything, but the specs are still faster with it enabled.

**Comment by jstorimer** [comment]
To shed a bit of light on this issue, and a proposed solution:

So when you include the 'rspec-rails' gem in your Gemfile and do the `Bundler.require` thing (happens in `config/application.rb`) it will attempt to `require 'rspec-rails'`. This file exists and is the `Railtie` for 'rspec-rails'. It doesn't load the library code supplied by 'rspec-rails'.

In the rspec projects I have worked on the `spec/spec_helper.rb` looks like this: https://github.com/ryanb/railscasts/blob/master/spec/spec_helper.rb#L7-11

So it seems that 'rspec/rails' is meant to be loaded after your environment is loaded which explains the speedboost you guys were getting from preloading it. Looks like the same is true for capybara.

I benchmarked the different requires ('rspec', 'rspec/rails', and 'rspec/autorun') and 'rspec/rails' was by far the biggest gain.

After giving this some thought I think the right solution is to revert this commit and provide a general purpose way to preload more stuff. I still want to keep this outside of your application code, spork has proven to me that that's not the way to go.

I'm thinking that we support a `.spin` file. If it exists in the cwd when the server is booted then it'll load that after loading `config/application.rb`. You could then put your `rspec/rails` and `capybara/rspec` stuff right in there along with any other custom behaviour you want to set up.

Thoughts?

**Comment by bittersweet** [comment]
Although it's a shame we can't give (Rspec for now) users this extra speedup out of the box I think this would be a good alternative.

Do you want to allow other configuration in that file as well? Kind of like the `.rspec` file where you can input commandline options like `--color`.

**Comment by maprihoda** [comment]
The idea of supporting a `.spin` file seems to be very attractive at the first sight. However:
- for any other custom behaviour/configuration (at least for rspec and capybara) we would have to load config/environment (which we don't want to do as it would preload the whole app and thus make Spin useless)
- yes, it's 'rspec/rails' that makes the difference. Preloading other gems ('capybara/rspec', 'capybara/rails') adds only a very, very tiny bit to the speed up. So what other libraries would be required in the `.spin` file to justify its existence?

**Comment by jstorimer** [comment]
@bittersweet: I was imagining it just being a regular Ruby file. So no special options.

@maprihoda: Great points. Perhaps we'll get the most mileage here by just preloading 'rspec/rails' and not mucking things up with custom configurations. Personally I can't think of anything else that needs to go in that file besides 'rspec/rails'. Since this project is meant for Rails apps I'm ok with preloading a rails-specific file.

**Comment by maprihoda** [comment]
I think preloading  'rspec/rails', and perhaps 'rspec/autorun' should be enough

**Comment by jstorimer** [comment]
Agreed. Done.

**Pull request merged**
