### PR TITLE
Add SIGQUIT handling for re-running the last files ran.

### PR DESCRIPTION
**Pull request by jtrim**
This pull request:
- Extracts the forking logic to a method
- Adds signal handling to re-run the last files ran
- Documents the changes

Let me know if you spot any changes you'd like to see made, I'd be happy to make tweaks. Thanks!

Jesse

### CODE REVIEW

**Comment by jstorimer** [comment]
I tried this on both an rspec project and a test-unit project and both failed. The code looks sane to me so I'm not sure what the issue is.

Is it working for you?

Here's the trace from the test-unit proj: https://gist.github.com/22e242430ec823a6eec9
And from the rspec proj: https://gist.github.com/702db7bd61d512b0f834

**Comment by jtrim** [comment]
Yeah, I used it all day yesterday on a project running rspec. I'll look into it. Thanks!

**Comment by jtrim** [comment]
Now I'm seeing some weird stuff that I didn't notice yesterday related to the terminal bell activating several times after exiting from `spin serve`. Looking into it.

**Comment by jstorimer** [comment]
This is working for me without issue now. Let me know if this is good to merge or if you're still seeing issues.

**Comment by jtrim** [comment]
I can't reproduce the problem I was seeing before on a different computer...must have been something with its configuration if you can't see it either. I think it's good to merge. Thanks!

**Pull request merged**
