### PR TITLE
Signal handlers

### PR DESCRIPTION
**Pull request by jdelStrother**
In Ruby 2.0, when I hit Ctrl-\ to re-run my last spec, I get the following: 

```
^\log writing failed. can't be called from trap context
/Users/jon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/rails-a9d4fa337af4/activesupport/lib/active_support/dependencies.rb:251:in `require': can't be called from trap context (ThreadError)
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/rails-a9d4fa337af4/activesupport/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/rails-a9d4fa337af4/activesupport/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/rails-a9d4fa337af4/activesupport/lib/active_support/dependencies.rb:251:in `require'
        from /Users/jon/Developer/web/spec/helpers/comments_helper_spec.rb:1:in `<top (required)>'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/rails-a9d4fa337af4/activesupport/lib/active_support/dependencies.rb:245:in `load'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/rails-a9d4fa337af4/activesupport/lib/active_support/dependencies.rb:245:in `block in load'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/rails-a9d4fa337af4/activesupport/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/rails-a9d4fa337af4/activesupport/lib/active_support/dependencies.rb:245:in `load'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `block in load_spec_files'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `each'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `load_spec_files'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:22:in `run'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `block in autorun'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:321:in `fork'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:321:in `fork_and_run'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:197:in `sigquit_handler'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:178:in `block in rerun_last_tests_on_quit'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:145:in `call'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:145:in `accept'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:145:in `run_pushed_tests'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:42:in `block (2 levels) in serve'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:41:in `loop'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:41:in `block in serve'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:257:in `open_socket'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin.rb:36:in `serve'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/lib/spin/cli.rb:43:in `run'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/gems/spin-0.7.0/bin/spin:3:in `<top (required)>'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/bin/spin:23:in `load'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/bin/spin:23:in `<main>'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
        from /Users/jon/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
log writing failed. can't be called from trap context
```

This PR replaces the signal handling behaviour with the self-pipe trick (https://gist.github.com/mrnugget/4769939), moving the invocation of sigquit_handler() & sigint_handler() to the main event loop.

The first commit in this PR is mostly just shuffling code around so that the changes in the second commit are clearer.  I could squash them into a single one if you like.  Would welcome any comments on the cleanness/correctness of the code.

### CODE REVIEW

**Comment by toddmazierski** [comment]
@jdelStrother 

Thank you for this contribution! It came just in time &mdash; we're in the process of upgrading to Ruby 2.0 ourselves. Please note that I'm _not_ a maintainer. I can help test, though, and did have some feedback for you.

#### Bug

Description: pressing Ctrl+\ during test execution results in 3 (instead of 2) total test runs.

Steps to reproduce:
1. Push a test to Spin
2. While it's running, press Ctrl+\
3. Observe that the test is run a total of 3 times (twice _after_ Ctrl+\ is pressed)

My theory is that both the server _and_ forked processes are writing to the pipe. Could [`Spin.server_process?`](https://github.com/jdelStrother/spin/blob/ef645cacaff28ea0db6c85c0ec7855a9742e723c/lib/spin.rb#L78-L81) be of use here?

#### Dead code

Description: because the pipe acts as a queue, there is some synchronization code that can be deleted.

Locations:
1. I don't think [there's a need to check if the test process is alive here](https://github.com/jdelStrother/spin/blob/ef645cacaff28ea0db6c85c0ec7855a9742e723c/lib/spin.rb#L204-L207)
2. In fact, the entire [`Spin::TestProcess` class](https://github.com/jdelStrother/spin/blob/ef645cacaff28ea0db6c85c0ec7855a9742e723c/lib/spin/test_process.rb) could probably be deleted

I hope you find this useful! Please let me know if you have any questions.

**Comment by jdelStrother** [comment]
Thanks Todd, I haven't noticed the double-run thing.  I'll try & fix + clean up the other stuff & resubmit in the next couple of days

**Comment by jdelStrother** [comment]
@toddmazierski - thanks for the tips, they were useful.  See what you think to the additional commits.

**Comment by kirs** [comment]
@jdelStrother thanks for contributing! I'll check and merge it soon :+1:

**Comment by toddmazierski** [comment]
@jdelStrother Indeed, thank you!

Testing with 9aae453, I noticed there appears to be a bug with `SIGINT` handling. When Ctrl+C is pressed, the running test does not exit. Furthermore, now that signals are queued, I'm thinking we probably roll back the changes in #83.

Mind if I take a day or two to address these issues in a fork? I'll share my solution here for your review.

**Comment by kirs** [comment]
Yeah, I can see some issues with `SIGINT` too. Everything else works great on `2.0.0-p247`.

@toddmazierski I'm looking forward for your solution!

**Comment by jdelStrother** [comment]
Huh.  Which test framework are you guys using?  SIGINT seemed OK to me under RSpec

**Comment by kirs** [comment]
I tried it on Test::Unit.

## 

Kir Shatrov
+7 (929) 631-46-35

**Comment by toddmazierski** [comment]
> Which test framework are you guys using?

We're using [minitest](https://github.com/seattlerb/minitest) here!

[Here is my proposed fix](https://github.com/jdelStrother/spin/pull/1). Please let me know what you think. I should note that I've only tested these changes in Ruby 2.0 (I'll test in 1.9 over the weekend).

**Comment by toddmazierski** [comment]
`SIGINT` and `SIGQUIT` behavior appears to be consistent between Ruby 2.0 and 1.9. @kirs, I think this is ready for your review!

**Comment by kirs** [comment]
Thanks!

**Comment by kirs** [comment]
I've also released 0.7.1, now fully capable with MRI 2.0 :blush:

**Comment by toddmazierski** [comment]
Woo-hoo! :metal:

**Pull request merged**
