### PR TITLE
Add an ability to specify a line number for the RSpec (like in a README)

### PR DESCRIPTION
**Pull request by dkoprov**
After reading a README I've tried to specify a line number for test, but no luck.
After some research I studied an absence of this ability. So I've added it.

### CODE REVIEW

**Comment by dkoprov** [comment]
Oh, issue #9 is about this behavior. I wish I saw it earlier. But I didn't see a solution like I did in this PR.
Only one thing get me confused. An absence of determination: are we using rspec or not.

**Comment by dkoprov** [comment]
@jstorimer excuse me, but can you review this? It hangs out here for moth already, maybe I should rewrite this or smth?

**Comment by jstorimer** [comment]
This LGTM, but it says I can't auto-merge it. Would you rebase against the current master?

Sorry for the delay, I've been putting my spin energy into the rewrite. I'll try to ship it soon!

**Comment by dkoprov** [comment]
Rebased!
I saw in your twitter that you're in rush last couple of weeks, so thank you for your attention to this.

**Comment by jstorimer** [comment]
Thanks @dkoprov!

**Pull request merged**
