### PR TITLE
namespace everything

### PR DESCRIPTION
**Pull request by grosser**
now that we have tests -> move everything in a place that makes more sense, splitting up main/cli/hooks,
still lots of 'extract-method' to do but this is a first rough step

### CODE REVIEW

**Comment by grosser** [comment]
I chose to make everything static methods and wrap the into `class << self` so private works as expected

**Comment by jstorimer** [comment]
I said back when the project started (https://github.com/jstorimer/spin/pull/5#issuecomment-2599756) that I didn't want to split out the code into a bunch of files in lib/. I still believe that the code base is small enough to keep it all in `bin/spin` but I want to open this up for discussion and see what others think.

I personally don't see much gain from this. Having everything refactored into classes with class methods makes the code harder to find and harder to follow the path of execution. Keeping everything in one file means less overhead for grokking the source and, ultimately, for contributing. You say this 'makes more sense' but I don't see the gain.

What does everyone else think? Does this make the code more maintainable? Understandable? Easier to debug?

/cc @dstrelau @bittersweet @maprihoda

**Comment by grosser** [comment]
Hmm I'd say

pro:
- unit-testable
- potentially reusable by someone else
- encourages information hiding/small methods instead of 30+ line methods with 7 random arguments
- possible to stub/hack/overwrite via hooks
- smaller / easily digestible chunks

con:
- harder to follow execution because of indirection
- harder to see what's going on
- less instantly hackable

I kind of just feel dirty dealing with a bunch of global/unreusable methods.
A path I could also imagine is keeping options parsing in the bin/spin and putting everything else into one lib/spin.rb

**Comment by jstorimer** [comment]
I'm on board :)

I am in favour of keeping option parsing in `bin/spin` but that can be refactored later.

**Pull request merged**
